---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/importers":
    post:
      summary: Create an importer
      tags:
      - Importers
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  importer:
                    type: object
                    properties:
                      id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - created_at
                    - updated_at
                    - url
                required:
                - importer
        '422':
          description: unprocessable content
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      file:
                        type: array
                        items:
                          type: string
                        example:
                        - must be filled
                    required: []
                required:
                - errors
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: file
    get:
      summary: Get an importer list
      tags:
      - Importers
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                propeerties:
                  importers:
                    type: object
                    properties:
                      id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - created_at
                    - updated_at
                    - url
                  meta:
                    current_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_count:
                      type: integer
                    per_page:
                      type: integer
                required:
                - importers
                - meta
  "/importers/{id}":
    get:
      summary: Get an importer
      tags:
      - Importers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  importer:
                    type: object
                    properties:
                      id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - created_at
                    - updated_at
                    - url
                required:
                - importer
        '404':
          description: not found
  "/stores":
    get:
      summary: Get an store list
      tags:
      - Stores
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                propeerties:
                  stores:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      owner_name:
                        type: string
                      balance:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - name
                    - owner_name
                    - balance
                    - created_at
                    - updated_at
                    - url
                  meta:
                    current_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_count:
                      type: integer
                    per_page:
                      type: integer
                required:
                - stores
                - meta
  "/stores/{id}":
    get:
      summary: Get an store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  store:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      owner_name:
                        type: string
                      balance:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - name
                    - owner_name
                    - balance
                    - created_at
                    - updated_at
                    - url
                required:
                - store
        '404':
          description: not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
