---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/importers":
    post:
      summary: Create an importer
      tags:
      - Importers
      security:
      - ApiKeyAuth: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  importer:
                    type: object
                    properties:
                      id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - created_at
                    - updated_at
                    - url
                required:
                - importer
        '422':
          description: unprocessable content
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      file:
                        type: array
                        items:
                          type: string
                        example:
                        - must be filled
                    required: []
                required:
                - errors
        '401':
          description: unauthorized
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: file
    get:
      summary: Get an importer list
      tags:
      - Importers
      security:
      - ApiKeyAuth: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  importers:
                    type: array
                    items:
                      properties:
                        id:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        url:
                          type: string
                      required:
                      - id
                      - created_at
                      - updated_at
                      - url
                  meta:
                    current_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_count:
                      type: integer
                    per_page:
                      type: integer
                required:
                - importers
                - meta
        '401':
          description: unauthorized
  "/api/v1/importers/{id}":
    get:
      summary: Get an importer
      tags:
      - Importers
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  importer:
                    type: object
                    properties:
                      id:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - created_at
                    - updated_at
                    - url
                required:
                - importer
        '404':
          description: not found
        '401':
          description: unauthorized
  "/api/v1/stores/{store_id}/movements":
    get:
      summary: Get an movement list
      tags:
      - Movements
      security:
      - ApiKeyAuth: []
      parameters:
      - name: store_id
        in: path
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  movements:
                    type: array
                    items:
                      properties:
                        id:
                          type: string
                        kind:
                          type: string
                        occurred_on:
                          type: string
                        value:
                          type: string
                        personal_code:
                          type: string
                        card_number:
                          type: string
                        occurred_at:
                          type: string
                        store_id:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        url:
                          type: string
                      required:
                      - id
                      - kind
                      - occurred_on
                      - value
                      - personal_code
                      - card_number
                      - occurred_at
                      - store_id
                      - created_at
                      - updated_at
                      - url
                  meta:
                    current_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_count:
                      type: integer
                    per_page:
                      type: integer
                required:
                - movements
                - meta
        '401':
          description: unauthorized
  "/api/v1/stores/{store_id}/movements/{id}":
    get:
      summary: Get an movement
      tags:
      - Movements
      security:
      - ApiKeyAuth: []
      parameters:
      - name: store_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  kind:
                    type: string
                  occurred_on:
                    type: string
                  value:
                    type: string
                  personal_code:
                    type: string
                  card_number:
                    type: string
                  occurred_at:
                    type: string
                  store_id:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                  url:
                    type: string
                required:
                - id
                - kind
                - occurred_on
                - value
                - personal_code
                - card_number
                - occurred_at
                - store_id
                - created_at
                - updated_at
                - url
        '404':
          description: not found
        '401':
          description: unauthorized
  "/api/v1/stores":
    get:
      summary: Get an store list
      tags:
      - Stores
      security:
      - ApiKeyAuth: []
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  stores:
                    type: array
                    items:
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        owner_name:
                          type: string
                        balance:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        url:
                          type: string
                      required:
                      - id
                      - name
                      - owner_name
                      - balance
                      - created_at
                      - updated_at
                      - url
                  meta:
                    current_page:
                      type: integer
                    total_pages:
                      type: integer
                    total_count:
                      type: integer
                    per_page:
                      type: integer
                required:
                - stores
                - meta
        '401':
          description: unauthorized
  "/api/v1/stores/{id}":
    get:
      summary: Get an store
      tags:
      - Stores
      security:
      - ApiKeyAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  store:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      owner_name:
                        type: string
                      balance:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      url:
                        type: string
                    required:
                    - id
                    - name
                    - owner_name
                    - balance
                    - created_at
                    - updated_at
                    - url
                required:
                - store
        '404':
          description: not found
        '401':
          description: unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
