development:
  adapter: redis
  url: <%= ENV.fetch("CACHE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: file_parser_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("CACHE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: file_parser_production
