default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["DATABASE_DEVELOPMENT_HOST"] %>
  port: <%= ENV["DATABASE_DEVELOPMENT_PORT"] %>
  username: <%= ENV["DATABASE_DEVELOPMENT_USER"] %>
  password: <%= ENV["DATABASE_DEVELOPMENT_PASSWORD"] %>
  database: file_parser_development

test:
  <<: *default
  host: <%= ENV["DATABASE_TEST_HOST"] %>
  port: <%= ENV["DATABASE_TEST_PORT"] %>
  username: <%= ENV["DATABASE_TEST_USER"] %>
  password: <%= ENV["DATABASE_TEST_PASSWORD"] %>
  database: file_parser_test

production:
  <<: *default
  host: <%= ENV["DATABASE_PRODUCTION_HOST"] %>
  port: <%= ENV["DATABASE_PRODUCTION_PORT"] %>
  username: <%= ENV["DATABASE_PRODUCTION_USER"] %>
  password: <%= ENV["DATABASE_PRODUCTION_PASSWORD"] %>
  database: file_parser_production
